version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: galvao-apps-for-devs-vscode_server_1
      APP_PORT: 8080

  server:
    image: codercom/code-server:latest
    restart: on-failure
    user: "1000:1000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA_DIR}/data:/home/coder
      - ${APP_DATA_DIR}/workspace:/home/coder/workspace
    environment:
      PASSWORD: $APP_PASSWORD
    privileged: true
    comand: /bin/bash -c "sudo apt-get update && sudo apt-get install -y docker.io && sudo usermod -aG docker coder"