version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: galvao-apps-for-devs-vscode_server_1
      APP_PORT: 8080

  server:
    build: .
    restart: on-failure
    user: "1000:1000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA_DIR}/data:/home/coder
      - ${APP_DATA_DIR}/workspace:/home/coder/workspace
    environment:
      PASSWORD: $APP_PASSWORD
    privileged: true