version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: galvao-apps-for-devs-vscode_server_1
      APP_PORT: 8080

  server:
    image: ghcr.io/lucasgalvaonunes/vscode-server:latest
    restart: on-failure
    user: "1000:1000"
    ports:
      - "9003:9003"
    group_add:
      - 994
    volumes:
      - ${APP_DATA_DIR}/workspace:/home/coder
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PASSWORD: $APP_PASSWORD
    privileged: false