FROM codercom/code-server:latest

# USER root
# # Instalar Docker CLI
# RUN apt-get update && apt-get install -y docker.io && usermod -aG docker coder

# Iniciar o container como usuário 1000:1000
USER "1000:1000"
