version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: galvao-apps-for-devs-vscode_server_1
      APP_PORT: 3030
  server:
    image: codercom/code-server:latest
    restart: on-failure
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data:/home/coder
    environment:
      PASSWORD: $APP_PASSWORD
    privileged: false

