version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: galvao-apps-for-devs-vscode_server_1
      APP_PORT: 8080
  docker:
    image: docker:27.2.0-dind@sha256:f9f72ad901a78f27be922b2d320bbc263174f12919c1b37e6a01f828fa904565
    privileged: true
    network_mode: host
    stop_grace_period: 1m
    restart: on-failure
    environment:
      DOCKER_ENSURE_BRIDGE: "dind0:10.32.0.1/16"
    entrypoint: sh /entrypoint.sh
    command: >
      dockerd
        --bridge dind0
        --data-root /data/data
        --exec-root /data/exec
        --host unix:///data/docker.sock
        --pidfile /data/docker.pid
    volumes:
      - ${APP_DATA_DIR}/data/docker/entrypoint.sh:/entrypoint.sh
      - ${APP_DATA_DIR}/data/docker:/data
  server:
    image: codercom/code-server:4.98.2@sha256:9ed588a05d4e81aa464e753a409bc3b2b93267323d1c3975fbddf6f9aef84c26
    restart: on-failure
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data:/home/coder
      - ${APP_DATA_DIR}/data/docker/docker.sock:/var/run/docker.sock
    environment:
      PASSWORD: $APP_PASSWORD