version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: galvao-apps-for-devs-vscode_server_1
      APP_PORT: 8080

  docker:
    image: docker:dind
    privileged: true
    network_mode: bridge
    environment:
      DOCKER_TLS_CERTDIR: ""
      DOCKER_ENSURE_BRIDGE: "dind0:10.32.0.1/16"
    command: >
      dockerd
        --bridge dind0
        --data-root /var/lib/docker
        --exec-root /data/exec
        --host tcp://0.0.0.0:2375
        --pidfile /data/docker.pid
    volumes:
      - dind-storage:/var/lib/docker

  server:
    image: ghcr.io/lucasgalvaonunes/vscode-server:latest
    depends_on:
      - docker
    restart: on-failure
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data:/home/coder
      - dind-storage:/var/lib/docker
    environment:
      PASSWORD: $APP_PASSWORD
      DOCKER_HOST: tcp://docker:2375
    privileged: false

volumes:
  dind-storage: