version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: galvao-apps-for-devs-vscode_server_1
      APP_PORT: 8080

  server:
    build:
      context: ./code-server
      dockerfile: Dockerfile
    restart: on-failure
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data:/home/coder
    environment:
      PASSWORD: $APP_PASSWORD